### ISSUE TITLE
建议增加一个日志

### ISSUE THREAD

**Issue by Adek06** [kesin/taskover#5]
比如在板块1里 用户 A 点击 over 项目 a 后，在侧边上显示 A over a

![image](https://user-images.githubusercontent.com/25602645/70513746-2ab34b80-1b6d-11ea-873c-bafd53840fd8.png)

**Comment by kesin** [comment]
基本都在Gitee维护issue，所以这里不常看，不好意思哈，这个后面空了也会考虑上 :)
