### ISSUE TITLE
登录之后从详情回到主页 每次都有 flash message

### ISSUE THREAD

**Issue by springwq** [kesin/taskover#6]
![Screen Shot 2019-12-11 at 10 36 37 AM](https://user-images.githubusercontent.com/2961548/70586519-4288df00-1c02-11ea-9996-54e5d04d4037.png)

**Comment by kesin** [comment]
好的，晚些看下

**Comment by kesin** [comment]
这个是Rails页面缓存的问题，暂时不作处理了 😄
